### ISSUE TITLE
Missing LICENSE / COPYING file.

### ISSUE THREAD

**Issue by peterjc** [TGAC/Aequatus-Browser#1]
According to the ``README`` file, you are using the GNU General Public License as published by the Free Software Foundation, at version 3 of the License.

With GPL it is traditional to include a copy of the licence as a file named ``COPYING`` - see https://www.gnu.org/licenses/gpl-howto.html - alternatively GitHub recommends ``LICENSE`` instead https://help.github.com/articles/open-source-licensing/

**Comment by anilthanki** [comment]
Added a licence copy as well text in readme.md
